AMF pod crash when Mobile data disabled and re-enabled in UE
omec-project/amf pull request #290
Opened 2024-08-28 13:50 UTC by ashithacdac

This is to avoid an AMF pod crash when mobile data is disabled and re-enabled in UE.

2024-08-28 14:18 UTC, thakurajayL commented
Thank You for providing fix. Could you please provide pcap as well. May help understand RCA better.

2024-08-29 05:14 UTC, ashithacdac commented
Yeah Sure.
[Mobile_Data_Toggle.zip](https://github.com/user-attachments/files/16792351/Mobile_Data_Toggle.zip)

2024-08-29 19:47 UTC, gab-arrobo requested changes

2024-08-29 19:47 UTC, gab-arrobo commented on ngap/handler.go
> +						ranUe.Log.Errorf("SmContext[PDU Session ID:%d] not found", pduSessionID)
Agree with @thakurajayL that `continue` is the appropriate way to handle this case.

2024-08-30 06:40 UTC, closed without merging

2024-08-30 07:34 UTC, ashithacdac commented
By mistake, I have deleted the earlier branch. Incorporated the requested changes in the PR. Please check the same.
https://github.com/omec-project/amf/pull/291